### ISSUE TITLE
Ctrl+H key event is detected as BACKSPACE

### ISSUE THREAD

**Issue by laurent22** [cronvel/terminal-kit#101]
A simple test is the one from the doc:

```
var term = require( 'terminal-kit' ).terminal ;

function terminate() {
	term.grabInput( false ) ;
	setTimeout( function() { process.exit() } , 100 ) ;
}

term.bold.cyan( 'Type anything on the keyboard...\n' ) ;
term.green( 'Hit CTRL-C to quit.\n\n' ) ;

term.grabInput( { mouse: 'button' } ) ;

term.on( 'key' , function( name , matches , data ) {
	console.log( "'key' event:" , name ) ;
	if ( name === 'CTRL_C' ) { terminate() ; }
} ) ;

term.on( 'terminal' , function( name , data ) {
	console.log( "'terminal' event:" , name , data ) ;
} ) ;

term.on( 'mouse' , function( name , data ) {
	console.log( "'mouse' event:" , name , data ) ;
} ) ;
```

If I press Ctrl+H, it prints BACKSPACE. Is that a bug in terminal-kit or some limitation of terminals in general?

**Comment by cronvel** [comment]
@laurent22 Some terminals generate `\x08` (which is Ctrl+H) as backspace, some other use `\x7f`.

In order to cover most terminals (which almost always advertise themself as 'xterm'), both characters are detected as the BACKSPACE key in Terminal Kit.

So Ctrl+H is a kind of forbidden shorthand in terminal application, like some other Ctrl+Letter, most notably:
- Ctrl+I is like TAB
- Ctrl+J is like `\n` (but Terminal Kit still generate a Ctrl+J, so you can use it if you want, but I won't recommend it)
- Ctrl+M is like ENTER or `\r`

**Comment by laurent22** [comment]
Thanks for the explanation, it makes sense. In my app users can define shortcuts and map them to actions, so the problem is that if they use Ctrl+H the action is never triggers (because terminal-kit gives Backspace). So I think I'm just going to map internally Ctrl+H to Backspace and that should make it work.

**Comment by cronvel** [comment]
Also the `matches` variable (see below) is an array of matching keys:
```js
term.on( 'key' , function( name , matches , data ) {
   // ...
} ) ;
```
For Backspace/Ctrl+H, it will be `['BACKSPACE','CTRL_H']`.
I still won't recommand using Ctr l+ H/I/J/M, like any terminal app does (vi, emacs in terminal mode, joe, nano, and so on...), because you will never now if the user had press Ctrl+Letter or the backspace/tab/enter/return key.
