### ISSUE TITLE
Fragment left behind by `screenBuffer.clear()`

### ISSUE THREAD

**Issue by GingkathFox** [cronvel/terminal-kit#102]
Hello!

I'm having a small issue. I'm making a terminal game, and it has a game loop. While making sure that the game objects are drawn right, i came across this issue: https://asciinema.org/a/7Kymc79uUCuWVdJ9v4rS1oL46

The loop is as follows:

```js
async function sleep(millis) {
    return new Promise(resolve => setTimeout(resolve, millis))
}
function update() {
    let mino = minos.randoMino()
    buf.clear()
    buf.draw()
    buf.put({x: 0, y: 0, markup: false, attr: {color: mino.color}}, mino.left.jetriminos())
    buf.put({x: 0, y: 5, markup: false}, mino.name)
    buf.draw()
}
async function run() {
    for (let i = 0; i < 10; i++) {
    update()
    console.log(i)
    await sleep(200)
    }
}

run()
```

Am i doing something wrong, or is `.clear()` just skipping over that one block? I've tried using `.fill()` with the same issue.

**Comment by GingkathFox** [comment]
Ok, apparently calling `term.clear()` instead of calling `buf.clear(); buf.draw()` works. Ima leave this open just incase anyone wants to discuss it.

**Comment by cronvel** [comment]
@GingkathFox You should not call `term.clear()`. Also I fail to understand your issue. On your video, what part of the screen is not properly cleared? It's hard to understand how your game should work.

**Comment by GingkathFox** [comment]
im just testing out `terminal-kit`. Heres a screenie of the forgotten fragment:

![Screen Shot 2019-11-05 at 6 59 10 PM](https://user-images.githubusercontent.com/33764485/68256509-5dae7080-fffe-11e9-9c80-8adde2e33070.png)

**Comment by cronvel** [comment]
@GingkathFox Ok, the blue square is the remnant of the previous sprite.
So... when you clear a ScreenBuffer instance, you make each cell **transparent**.
So when you draw the buffer on the terminal (which still has the previous *sprite* displayed), you don't overwrite the area where there is no data.

This behavior is consistent with how sprites work in any (non-ASCII) 2D lib, SDL for example. If you know a bit of SDL (or a similar framework), a screenBuffer is like a SDL surface. You can store sprite inside a screenBuffer and draw it on another screenBuffer or directly on the terminal, all of this transparency-wise.

If you want to achieve a Tetris in the terminal, some advice:
- I kind of deduce that your "minos" are not transparent from the fact that the blue artifact in your screenshot should extend to few more cell to the left, your "minos" sprite must be transparent everywhere there is nothing (thing it like a PNG image with transparency enable)
- I would recommend using one screenBuffer per minos, rather than re-using the same buffer again and again
- Your background should be a screenBuffer too, this one should not have transparency (it's not a sprite)

Basically, you start with a pure black opaque (no transparency) background. This background will work like a kind of accumulator, once a "mino" land, it should be printed (drawed) to this background. Before that, never draw a "mino" to the background.
Each mino has its own screenBuffer, each cell being either the color of this "mino" (if the cell is "solid"), or transparent (for empty cell).

You may also add a screenBuffer for the whole game area, it's not mandatory but it can help for the performance. It's often named a "damage buffer". That's this buffer that will be ultimately draw to the terminal, drawing only cells that have changed. Have a look to the *spaceship" demo, once inside the root directory of the package, run `./demo/spaceship.js`. Look at the code and how sprites are rendered.

When you draw to the terminal, you will first draw the background to the damage buffer, then you draw your current *flying/moving* mino, then you draw the damage buffer to the terminal with the delta option on (draw only changes). Only when a mino *lands*, you will *stamp* it on the background buffer, i.e. draw it on the background buffer.

Hope it helps!
