### ISSUE TITLE
grid or table drawing - help 

### ISSUE THREAD

**Issue by GabrielGab** [cronvel/terminal-kit#109]
Hi there , since I have discovered it, this tool help me a lot on my daily basis IOT projects.
I was wondering if there is some way to get a kind of **table or grid components** , may is some future feature in mind .

I am just needing a grid of about a few columns and a least 4 rows, **I am not thinking on inserting or deleting rows after creation.** 

Thanks in advance 
Gabriel

**Comment by TimvdEijnden** [comment]
I'm also looking for this, something like: https://www.npmjs.com/package/terminal-table

**Comment by cronvel** [comment]
@GabrielGab @TimvdEijnden As of v1.34.0, you can do this:
```js
var table = term.table( [
        [ 'header #1' , 'header #2' , 'header #3' ] ,
        [ 'row #1' , 'a much bigger cell '.repeat( 10 ) , 'cell' ] ,
        [ 'row #2' , 'cell' , 'a medium cell' ] ,
        [ 'row #3' , 'cell' , 'cell' ] ,
        [ 'row #4' , 'cell\nwith\nnew\nlines' , 'cell' ]
    ] , {
        width: 50 ,
        //height: 20 ,
        fit: true
    }
) ;
```
It's still experimental and undocumented, but you can already use it, the API could be considered **stable**.

Some other options: expandToWidth, shrinkToWidth, expandToHeight, shrinkToHeight, wordwrap (the 'fit' option simply activate all the 5 of them, the first 4 need a width or height options to work).

Options 'borderChars' can be 'light', 'lightRounded', 'heavy', 'double', 'dotted' or an object with the same structure found insde `lib/spChars.js`, defining chars for all line/corner/tee/cross.

As you can see, it supports word-wrapping out of the box and make use of a tons of new Terminal Kit features (still not quite documented) like the TextBuffer, the Document model, TextBox and so on... So it should be quite easy to add some nice features because there are probably already existing in widgets used behind the scene.

@GabrielGab @TimvdEijnden I would appreciate it if you test it and give me few feedback before I document it. There could be few bugs, cause under the hood it uses a new mode of rendering I will now use everywhere in Terminal-kit.

**Comment by cronvel** [comment]
@GabrielGab @TimvdEijnden As of v1.34.1, you can set a lot of attributes to display odd/even columns/rows/cells in different style, as well as Terminal-Kit markup support, and so on... 

You should check this out and try to comment/uncomment options to see it in action:
```js
const termkit = require( 'terminal-kit' ) ;
const term = termkit.terminal ;
term.table( [
        [ 'header #1' , 'header #2' , 'header #3' ] ,
        [ 'row #1' , 'a much bigger cell '.repeat( 10 ) , 'cell' ] ,
        [ 'row #2' , 'cell' , 'a medium cell' ] ,
        [ 'row #3' , 'cell' , 'cell' ] ,
        [ 'row #4' , 'cell\nwith\nnew\nlines' , 'cell' ]
    ] , {
        //hasBorder: false ,
        borderChars: 'lightRounded' ,
        borderAttr: { color: 'blue' } ,
        textAttr: { bgColor: 'default' } ,
        //textAttr: { bgColor: 'black' } ,
        firstCellTextAttr: { bgColor: 'blue' } ,
        firstRowTextAttr: { bgColor: 'gray' } ,
        firstColumnTextAttr: { bgColor: 'red' } ,
        //checkerEvenCellTextAttr: { bgColor: 'gray' } ,
        //evenCellTextAttr: { bgColor: 'gray' } ,
        //evenRowTextAttr: { bgColor: 'gray' } ,
        //evenColumnTextAttr: { bgColor: 'gray' } ,
        width: 50 ,
        //height: 20 ,
        fit: true , // Activate all expand/shrink + wordwrap
        //expandToWidth: true , shrinkToWidth: true , expandToHeight: true , shrinkToHeight: true , wordwrap: true ,
    }
) ;
```

Still waiting for your feedback ;)

**Comment by TimvdEijnden** [comment]
@cronvel 

Currently I've chosen for a simpler output that also works for me.

I've just tried this out, and it works and looks really nice. Great job!

**Comment by cronvel** [comment]
@TimvdEijnden Thanks for your feedback!
I just edited my previous post so that the last cell is featuring Terminal Kit's markup (works with `contentHasMarkup: true`).

**Comment by cronvel** [comment]
@TimvdEijnden  For the record, the full doc is now available [here](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.table) and [here](https://github.com/cronvel/terminal-kit/blob/master/doc/TextTable.md#top).
