### ISSUE TITLE
Terminal kit w/ readLineInterface doesn't allow me to type stuff in after.

### ISSUE THREAD

**Issue by ethans333** [cronvel/terminal-kit#128]
When I use terminal kit's single column menu, get the response and then call a function that uses readLineInterface, it wont let me type in anything.

```javascript
    term.singleColumnMenu(["tracks", "artist"], function(error, response){
        if(response.selectedText == "tracks"){
            console.clear()
            searchTracks.searchTracks()
        } else {
            console.clear()
            searchArtist.searchArtist()
        }
    });

```
```javascript
let searchTracks = async () => {
    rl.question("Search for a track: ", async (inputTrack) => {
        let tracks = await getTracks(inputTrack);

        ...
}
```

**Comment by cronvel** [comment]
@ethans333 Why mixing *readline* and Terminal-Kit? Terminal-Kit already has inputs (e.g. `.inputField()`).

**Comment by cronvel** [comment]
@ethans333 I don't know exactly how *readline* works behind the scene, but they are probably interfering with each-other. For example `.singleColumnMenu()` set the terminal to what is called *raw mode* (it even supports the mouse). I don't know if *readline* turn the terminal to *raw mode* too, then exit this mode, or even if it need to... But whatever it does, it could cause major bugs in both *readline* and *Terminal Kit*, each one changing terminal mode without the other knowing.

That's why I highly suggest that you stick to *Terminal Kit* for all your terminal needs.

Look at the [doc](https://github.com/cronvel/terminal-kit/blob/master/doc/high-level.md#ref.inputField) for `.inputField()`, it can do everything you need and even more ;)
