### ISSUE TITLE
Document TextBox with markdown does not function as expected

### ISSUE THREAD

**Issue by NuSkooler** [cronvel/terminal-kit#146]
When using markdown within a  `TextBox` it is not rendered as expected.

Consider a `TextBox` with the following options:
```javascript
// ...
contentHasMarkup : true,
wordWrap : true,
```
Then call the following:
```javascript
const s = '^GRangers ^-^gare masters of the hunt, often living very independent lives or even occasionally as hermits. Skilled with ^Yranged weapons^-^g, ^GRangers ^-^gprefer to keep their enemies at a distance during combat.';
textbox.setContent(s, true);
```
Results look something like this:
![image](https://user-images.githubusercontent.com/1509339/104852855-65cc9600-58ba-11eb-8f98-13664e189748.png)

Expected:
", " and "prefer..." text should be "dim" Green.

Another oddity that I'm not sure is expected: "^Gfoo ^gbar" I would expect to be bright Green "Foo" and dim "bar", but I seem to have to insert `^-` between since the bright toggles on?

**Comment by cronvel** [comment]
@NuSkooler `^G` is for "brightGreen", so "Rangesr" should be displayed as it should. "prefer..." should be dimmed, so there is something wrong here. But I can't reproduce it: it works as it should on my side. My terminal also support dimmed bright colors, the second "Rangers" appears darker than the first.
Can you check that your terminal (which?) has correct handling for the "dim" attribute?

**Comment by NuSkooler** [comment]
@cronvel I can reproduce this in [MagiTerm](https://blog.talismanbbs.com/magiterm/), [SyncTERM](https://syncterm.bbsdev.net/), [NetRunner](http://www.mysticbbs.com/downloads.html) and Elementary OS's [Terminal](https://github.com/elementary/terminal) with term type "xterm".

But yes, they all support bold/dim. 

Here are sequences rendered by other working systems (0x1b replaced with $):
```
$[0;1;40;32mRangers$[0;32m are masters of the hunt, often living very independent lives or even occasionally as hermits. Skilled with $[1;33mranged weapons$[0;32m, $[1mRangers$[0;32m prefer to keep their enemies at a distance during combat$[37m.
```

**Comment by NuSkooler** [comment]
Here is what is being rendered:
```
$[3;46H$[0m$[1m$[32m$[40mRangers $[32m$[2mare masters of the $[4;46Hhunt, often living very $[39m$[49m$[22m    $[5;46H$[32m$[40m$[2mindependent lives or even $[39m$[49m$[22m    $[6;46H$[32m$[40m$[2moccasionally as hermits. $[39m$[49m$[22m    $[7;46H$[32m$[40m$[2mSkilled with $[1m$[33mranged weapons$[32m, $[39m$[49m$[22m $[8;46H$[1m$[32m$[40m$[2mRangers $[32mprefer to keep their $[39m$[49m$[22m $[9;46H$[32m$[40m$[2menemies at a distance during $[10;46Hcombat.$[39m$[49m$[22m                       $[11;46H                            $[12;46H                    
```

**Comment by cronvel** [comment]
@NuSkooler Sorry I'm a bit lost. Did you mean that it does not work with your ansi-bbs termconfig + bbs terminal app, or that it doesn't even work with xterm + xterm config?

On my end, this sample works fine with xterm, or gnome-terminal: 

```js
const termkit = require( 'terminal-kit' ) ;
const term = termkit.terminal ;

term.clear() ;

var text = '^GRangers ^-^gare masters of the hunt, often living very independent lives or even occasionally as hermits. Skilled with ^Yranged weapons^-^g, ^GRangers ^-^gprefer to keep their enemies at a distance during combat.';

var document = term.createDocument() ;

var textBox = new termkit.TextBox( {
    parent: document ,
    content: text ,
    contentHasMarkup: true ,
    wordWrap: true ,
    x: 10 ,
    y: 2 ,
    width: 30 ,
    height: 15
} ) ;

term.moveTo( 1 , 18 ) ;
process.exit() ;
```
Tested Elementary Terminal, it seems to not support dim + bright color (bright green + dim appears green + dim). Konsole (KDE) does the same. 
That's why I asked you to check how dim behaves on your terminal, because there are many terminal where it does not make sense to mix dim + bright color. To be honest, I just don't know how it should behave: `dim < normal < dim+bright < bright` or `dim < dim+bright < normal < bright`? On my terminal dim+bright = normal.
I would highly suggest to just avoid that.

But maybe there is another thing that is misunderstood: **markup is cumulative**. For example your second "^GRangers" adds bright green to an already dimmed text-attribute. Usually you have to style-reset, using either `^:`, or the handy `^ ` (that reset AND space, allowing things like `lorem ^+bold^ ipsum`), or the new *special reset* `^;`.

> Another oddity that I'm not sure is expected: "^Gfoo ^gbar" I would expect to be bright Green "Foo" and dim "bar", but I seem to have to insert ^- between since the bright toggles on?
Also there is no *bright toggle*, unlike dim which is an attribute on its own, bright color are simply 8 regular ansi color that appears brighter than the first 8 ansi color. Except that the previous statement holds: terminals are not consistent while applying "dim" on those colors, neither it is when applying it to the 256-color palette or true-color.
Or at least it is how it works on all *nix terminals I'm aware of.

**Comment by NuSkooler** [comment]
@cronvel I have reproduced this with term and generic set to "xterm" as well as with them set to "ansi-bbs" (which uses the previously attached terminfo) using all of the listed terminals.

I don't _want_ to use dim at all. That was an attempt to fix around bright/regular colors only (e.g. '^GBright Green ^gRegular Green').

I will create a more minimal example. Are there specifics you want me to capture/test?

**Comment by cronvel** [comment]
@NuSkooler Ok post me the whole sample code. But I have a lot of work this week, I don't know if I can check/fix something anytime soon.

**Comment by NuSkooler** [comment]
@cronvel No worries, I know this is a one man job right now!

OK after further Inspecting what the Markup produces and your statement above, this makes more sense. It just didn't meet my expectations at all I guess coming from other systems such as `|##` pipe codes and some popular syntax used in MUDs.

Is there reasoning to have it so complex? I'd think generally people are trying to do what I'm doing where:
`^GBright Green ^gGreen ^YBright Yellow ^yYellow/Brown` would produce a ESC sequence showing the named colors.

This produces the expected results:
`^g^+Bright Green^ ^gGreen^ ^y^+Bright Yellow^ ^yYellow/Brown`

In pipe code land this is:
`|10Bright Green |02Green |14Bright Yellow |06Yellow/Brown`

I guess my other alternative is to set `contentHasMarkup` to `ansi` and just use Pipe codes and/or I'm happy to submit a PR to allow for this simplified approach as well (e.g. `contentHasMarkup: 'pipe'`).

BTW one more minor issue related to this: Switching to this string renders a space before the comma, but otherwise works:
`^g^+Rangers^ ^gare masters of the hunt, often living very independent lives or even occasionally as hermits. Skilled with ^y^+ranged weapons^ ^g, ^g^+Rangers^ ^gprefer to keep their enemies at a distance during combat.`

**Comment by cronvel** [comment]
@NuSkooler I think there is some misunderstanding on both side, maybe the fact I'm not a native english speaker get in the way. So I will try to explain myself again.

All markups with letter (i.e. ^ followed by a letter, like `^g` or `^G`) are one of the 16 colors, every time the uppercase letter counterpart is for the bright version. Note that bright is not an attribute (e.g. unlike dim) in my lib, it is not an attribute too from the terminal POV (at least for all terminal I'm aware of). It's just the name of the color.

Hence `^GBright Green ^gGreen ^YBright Yellow ^yYellow/Brown` should do exactly what you expect: turn to bright green, write "Bright Green", turn to green, write "Green", etc...

If it doesn't, then there is a bug somewhere. If we can't find it out, I will need to test it first hand. 

But your second example: `^g^+Bright Green^ ^gGreen^ ^y^+Bright Yellow^ ^yYellow/Brown` that is working for you, seems a proof that your term is working like the kernel's builtin linux console (which is **not** xterm-compatible), where **bold** does not produce bold but brighter colors. And since *bold* and *color* are different properties, bold is not turned off when you change the color. That explains what you are experiencing, and the need for a reset that seems complex to you.

If that's the case, in your BBS termconfig, just add the escape sequence for nobold and bold for each ANSI colors and their bright counterpart. That's what I've done for the linux console (if I remember well).

Also, like I said earlier: `^ ` is a style-reset + a space (it's a short hand), if you don't want a space (e.g. before your comma), use `^:` which reset without outputting any char. The `^ ` was added because I found it easier to read.

I think I will have to install some of those BBS terminal if we want to make progress on that.

**Comment by NuSkooler** [comment]
@cronvel xterm supports a number of color "modes":
* The original 8 colors with "bold" variants. These are the "bright" versions of the 8 colors (https://en.wikipedia.org/wiki/ANSI_escape_code#Colors has a fairly good explanation). I don't know of any terminals that do not support this. This has been around since the 90's.
* 8-bit / 256-color (indexed and named)
* 24-bit / true color (RGB)

Here is xterm displaying the same test ANSI file of which the contents I posted above with the bold toggles and it's hex dump:
![image](https://user-images.githubusercontent.com/1509339/105046664-9df0e780-5a26-11eb-82a7-2b8b6080815a.png)

I want to achieve exactly that. Perhaps I need tweaks to the `ansi-bbs.js` file, but I'm not seeing how to do it.

If you look at my ansi-bbs-utils library, you can see how I support all 3 (and actually more) color modes.
https://github.com/NuSkooler/ansi-bbs-utils/tree/master/lib (see the color_* JS files). This also allows RGB -> 256 -> 16c.

Perhaps what I need is a way to make `ansi-bbs.js` (my terminfo) produce the 16c using the dim/bright toggles (which again, is the 1990's and beyond standard)

**Comment by cronvel** [comment]
@NuSkooler That's true there are settings to make bold appears bright in most term. Didn't remembered that xterm does that by default. This is one of those bad legacy behavior IMHO. I just want bold to produce bold, and don't mess with the color. On my terminal your sequence does not change the color.

If a terminal does not support **bold** (<-- I mean bold in the *font* sense), but instead shift to the bright color, its termconfig must have bold/nobold escape sequence before each color sequence.

See what I've done here (kernel's builtin console):

```js
const bold = '\x1b[1m' ;
const noBold = '\x1b[22m' ;
const blink = '\x1b[5m' ;
const noBlink = '\x1b[25m' ;
const defaultColor = noBold + '\x1b[39m' ;      // back to the default color, most of time it is the same than .white
const bgDefaultColor = noBold + '\x1b[49m' ;    // back to the default color, most of time it is the same than .bgBlack

const esc = tree.extend( null , Object.create( xterm.esc ) , {
    // Clear screen
    clear: { on: '\x1b[H\x1b[J' } ,

    // Linux console doesn't have bright color code, they are produced using 'bold' (which is not bold, by the way...)
    defaultColor: { on: defaultColor } ,
    black: { on: noBold + '\x1b[30m' , off: defaultColor } ,
    red: { on: noBold + '\x1b[31m' , off: defaultColor } ,
    green: { on: noBold + '\x1b[32m' , off: defaultColor } ,
    yellow: { on: noBold + '\x1b[33m' , off: defaultColor } ,
    blue: { on: noBold + '\x1b[34m' , off: defaultColor } ,
    magenta: { on: noBold + '\x1b[35m' , off: defaultColor } ,
    cyan: { on: noBold + '\x1b[36m' , off: defaultColor } ,
    white: { on: noBold + '\x1b[37m' , off: defaultColor } ,
    darkColor: { on: noBold + '\x1b[3%um' , off: defaultColor } ,   // should be called with a 0..7 integer
    brightBlack: { on: bold + '\x1b[30m' , off: defaultColor } ,
    brightRed: { on: bold + '\x1b[31m' , off: defaultColor } ,
    brightGreen: { on: bold + '\x1b[32m' , off: defaultColor } ,
    brightYellow: { on: bold + '\x1b[33m' , off: defaultColor } ,
    brightBlue: { on: bold + '\x1b[34m' , off: defaultColor } ,
    brightMagenta: { on: bold + '\x1b[35m' , off: defaultColor } ,
    brightCyan: { on: bold + '\x1b[36m' , off: defaultColor } ,
    brightWhite: { on: bold + '\x1b[37m' , off: defaultColor } ,
    brightColor: { on: bold + '\x1b[3%um' , off: defaultColor } ,   // should be called with a 0..7 integer

    // Linux console doesn't have bright bg color code, they are produced using 'blink' (which does not blink, by the way...)

    bgDefaultColor: { on: bgDefaultColor } ,
    bgBlack: { on: noBlink + '\x1b[40m' , off: bgDefaultColor } ,
    bgRed: { on: noBlink + '\x1b[41m' , off: bgDefaultColor } ,
    bgGreen: { on: noBlink + '\x1b[42m' , off: bgDefaultColor } ,
    bgYellow: { on: noBlink + '\x1b[43m' , off: bgDefaultColor } ,
    bgBlue: { on: noBlink + '\x1b[44m' , off: bgDefaultColor } ,
    bgMagenta: { on: noBlink + '\x1b[45m' , off: bgDefaultColor } ,
    bgCyan: { on: noBlink + '\x1b[46m' , off: bgDefaultColor } ,
    bgWhite: { on: noBlink + '\x1b[47m' , off: bgDefaultColor } ,
    bgDarkColor: { on: noBlink + '\x1b[4%um' , off: bgDefaultColor } ,  // should be called with a 0..7 integer
    bgBrightBlack: { on: blink + '\x1b[40m' , off: bgDefaultColor } ,
    bgBrightRed: { on: blink + '\x1b[41m' , off: bgDefaultColor } ,
    bgBrightGreen: { on: blink + '\x1b[42m' , off: bgDefaultColor } ,
    bgBrightYellow: { on: blink + '\x1b[43m' , off: bgDefaultColor } ,
    bgBrightBlue: { on: blink + '\x1b[44m' , off: bgDefaultColor } ,
    bgBrightMagenta: { on: blink + '\x1b[45m' , off: bgDefaultColor } ,
    bgBrightCyan: { on: blink + '\x1b[46m' , off: bgDefaultColor } ,
    bgBrightWhite: { on: blink + '\x1b[47m' , off: bgDefaultColor } ,
    bgBrightColor: { on: blink + '\x1b[4%um' , off: bgDefaultColor } ,  // should be called with a 0..7 integer

// ...
```

**Comment by NuSkooler** [comment]
@cronvel 
> This is one of those bad legacy behavior IMHO.

Maybe, but reality. One could argue it's bad to break long existing behavior as well.

The table above seems reasonable -- I have updated my `ansi-bbs.js` to use the codes above with unexpected results:
`focusLeftPadding: '^;^Y> '` produces e.g. `$[4;2H$[0m$[1m$[33m$[22m$[49m> $[1m$[37m$[25m$[46mRock`
move 4,2 -> reset -> bright -> yellow -> (normal -> defaultBG -> '>') ... 
![image](https://user-images.githubusercontent.com/1509339/105132734-a2f67b00-5aa8-11eb-9147-7a8d4c60ca35.png)

Where the normal->defaultBG comes from, I'm unsure. This of course borks the bright Yellow.

Even stranger, a `TextBox` with `content: [ '^GManage Characters', '^K-----------------']` produces:
`$[2;4H$[0m$[22m$[32m$[5m$[40mManage Characters$[3;4H$[1m$[30m-----------------`
...so I get blinking text.

I'm not sure where this stuff is coming from?

**Comment by cronvel** [comment]
@NuSkooler From your ansi-bbs.js:
```js
bgBrightRed: { on: blink + '\x1b[41m' , off: bgDefaultColor } ,
```
If the *blink* attribute produces a blink effect in your term, it means that is not the way to produce bright background colors.

**Comment by NuSkooler** [comment]
@cronvel No where am I asking for `bgBrightRed` or any other bright background color. If you look at the first example terminals with bright backgrounds would still not work since "normal -> defaultBG" was inserted. These are not in the Markup.

**Comment by cronvel** [comment]
@NuSkooler I'm saying you that that blink is coming from your termconfig, the `bgBrightRed` was the first line containing such reference to blink, I just copied the first occurrence.

It *really* works fine on my end. 

Also everything is backed by a ScreenBuffer, that's why you got some extra ESC seq. When a particular widget is drawn, it doesn't know what happened before, so it set everything that should be. Also each cell in the ScreenBuffer has some properties: defaultColor and the bgDefaultColor are, well, the default color of a cell. Everytime a ScreenBuffer surface is *blitted* it ensures each cell will be drawn with the correct color/attributes. It remembers color/attributes during that process so it only send necessary code *between cell*, but *not between surface blit* (everything can happen between 2 blits, including userland codes messing with attributes).

Also the markup was never meant to be a way of writing ESC seq, instead **it is meant to convey features of Terminal Kit**. You express what you want (color/attributes), the lib try its best to make it work across all supported platforms. E.g. *bold* in Terminal Kit is meant to write something using *bold font*. If the platform doesn't support bold font, the termconfig should fallback to what is as close as possible of *bold* (in a User eXperience sense), eventually just disable it if no clean fallback is possible, but not wildly send "\x1b[1m" because "hey, it's the bold code". The lib is supposed to abstract that away, the userland code may not even know how terminals work (and how messy they are).

**Comment by NuSkooler** [comment]
@cronvel I have to say it doesn't work as *expected* for me using a standard terminal + xterm.js due to the "unannounced" addition of colors. 

I think the termconfig files is exactly the abstraction you're describing, but the addition of the surprise attributes can make it quite hard for users of the library to customize the display to their liking.

I was able to get `ansi-bbs` to work how I want by adjusting the "bright background"s. This also works quite well with standard xterm (as I mentioned "ANSI-BBS" is simply a subset really). ElementaryOS's terminal application still displays an odd background color since CSI 49 is "default background" which it defines on it's own. It sounds like I can explicitly set one or more properties on parent elements (document or screen buffer) to bgBlack to counter this?

**Comment by cronvel** [comment]
@NuSkooler  Great PoC ;)

On your `ansi-bbs.js` termconfig, you need to turn off `deltaEscapeSequence: false` (at the end of the file). It should greatly improve the support. It tells the ScreenBuffer to fully reset color/attribute anytime a cell has different style that the previous one during a blit.

> It sounds like I can explicitly set one or more properties on parent elements (document or screen buffer) to bgBlack to counter this?

Yes, you can add an `attr` option to almost all widgets. Set it to `attr: { bgColor: 'black' }`. When attr is not set on a widget, it used the lib's default one, usually the terminal *default* color like CSI 49 for background. It could use some other *decent* default when it make more sense (e.g. highlighting a button).

**Comment by NuSkooler** [comment]
@cronvel Thank you that is very helpful!
