### ISSUE TITLE
Creating reusable components

### ISSUE THREAD

**Issue by NuSkooler** [cronvel/terminal-kit#148]
Looking for a quick rundown on creating my own reusable components within a Document. That is, a component made of 2:N terminal-kit elements that also has it's own methods that I can use across multiple documents.

Example: I want to create a "Character Frame" for my game. This may have something like 2-3 `TextView`'s that methods and listeners within my component would use to update them.

Is `Container` the correct class to base this around?

**Comment by cronvel** [comment]
@NuSkooler `Container` is probably the correct class for that. A container has its own sub ScreenBuffer, its children draw on that ScreenBuffer instead of drawing directly on the global Document's ScreenBuffer. If your Character Frame is a kind of *window* (or a *tab*), it's a good thing for it to have its own drawing surface, especially if it is movable/resizable.

Also, there exists a `Window` widget, which is a `Container` that has the *movable* flag and a window frame/border. At the moment only a mouse drag can move it around but it would be super-simple to add some key controls.

**Comment by NuSkooler** [comment]
Perfect thank you @cronvel
