### ISSUE TITLE
contentHasMarkup with 'ansi' produces incorrect ANSI sequence

### ISSUE THREAD

**Issue by NuSkooler** [cronvel/terminal-kit#155]
The fix in #153 now does properly honor the `contentHasMarkup: 'ansi'` option, but ANSI input is altered in unexpected ways before it is written to the stream.

Example (`$` representing 0x1b):
Input: `$[0;30m$[1;32mRando $[1;30m>> $[0;32mRace Selection`
Written out: `$[2;2H$[0m$[22m$[32m$[40m$[1mRando $[22m$[30m>> $[22m$[32m$[22mRace Selection$[22m$[39m`

The most relevant part is the `$[1;30m` before ">>" that is turned into a non-bold `$[22m$[30m`

Note that `^G${args.name}^- ^K>>^ ^gRace Selection` produces the correct ANSI. In my terminal definition this is bright black aka ^K aka grey:
`brightBlack: { on: bold + '\x1b[30m' , off: defaultColor } ,` with `bold` of `\x1b[1m`

**Comment by cronvel** [comment]
@NuSkooler It's an issue with the termconfig, like the other issue. TextBuffer/ScreenBuffer don't care about the original sequences, they parse them but store attributes using their own internal representation. Finally, when drawing on the actual terminal, they are regenerating sequences based on the active termconfig.

I'm closing this because it's not a new issue, but an issue with your terminal+termconfig combo (see the discussion on ansi-bbs).

**Comment by NuSkooler** [comment]
@cronvel you can see from the information above that is not the case:
* The equivalent markup works and produces the expected sequences
* "brightBlack" produces `ESC[1mESC[30m` -- the ANSI processing turns this into `ESC[22mESC[30m`

**Comment by cronvel** [comment]
@NuSkooler Sorry, but for Terminal Kit *brightBlack/gray* is `ESC[90m` (as input sequence, output depend on termconfig).

It's the same discussion we already had in the past, and where we are disagreeing :)

**Comment by NuSkooler** [comment]
@cronvel I think you're still missing the issue here. "brightBlack" is *not* `ESC[90m` for my terminal config. It produces `ESC[1mESC[30m`. Using this terminal config `^K` also produces the expected `ESC[1mESC30m` sequence.

When using "ansi" and passing in `ESC[1;30m`, Terminal Kit is turning that into `ESC[22mESC[30m`, which is clearly not matching what the terminal configuration describes for "brightBlack".

Kindly, this is not the same discussion but a bug.

**Comment by cronvel** [comment]
@NuSkooler If input comes from a pipe (stdin), it would make sense, but here it (is supposed to) comes from a human source (your script, or a file, a user input). 

Please, just don't ignore the fact that it goes through a ScreenBuffer that is rather **agnostic**. Again, a ScreenBuffer cell is a char + a color + some flags (bold, italic, underline, strike, etc). Again, *bold* is not understood as a color switch by Terminal Kit but as *displaying bold character* (font-weight). The input should convey an *universal* meaning, while the output (through the termconfig) should convey that meaning the best possible way depending on the terminal capability. 

* input: comes from a human (coder or end user)
* output: adaptive, translate into the terminal supported features

That's why **input** should not use termconfig (comes from human, not machine).

I understand it broke things on your end, but it would break equally (or even worse) for the other side of the coin if this logic had to be changed.

Also I think your way of thinking is too much tied to the actual produced terminal sequences, while the lib is intended to abstract away such a thing. It's like writing C++ code while thinking in ASM. Why don't you just use regular Terminal Kit markup? It's way easier to remember, less keystrokes, easier for eventual contributor, maintenance, and so on...

**Comment by cronvel** [comment]
@NuSkooler I added a 'legacyAnsi' option for your convenience as of v2.0.1. Also I still stick to the above statement that you may use Terminal Kit markup instead of escape sequences. When `contentHasMarkup: 'legacyAnsi'` is used, *bold* is understood as *make the foreground color brighter* (codes 1 and 22) and *blink* as *make the background color brighter* (codes 5 and 25).

To be honest, adding 'ansi' input was done for a specific use-case (someone wanted to highlight logs coming from another program, which seemed legit to me), but I'm not quite content with it, cause it leads to misunderstanding and misuses of the lib by users, and of course it increase the bug surface and maintenance cost on my side. 

It doesn't mix up well with the lib philosophy and I would be happier without it.

Anyway, I hope it will ease your life.

**Comment by NuSkooler** [comment]
@cronvel Thanks a ton for taking a stab at this - Unfortunately it doesn't seem to be working: Using the same input as the original post in this ticket but changing to `contentHasMarkup: 'legacyAnsi'` still produces the `ESC[22mESC[30m` sequence. Maybe I'm missing something else?

I fully understand _why_ this is happening and that TerminalKit wants to think of ESC sequences in a certain way. What I'm trying to push is that this isn't aligned with the reality of the situation. In the same that different terminals feed input from the keyboard or mouse differently, sources of colors are fed in differently as well. 

> If input comes from a pipe (stdin), it would make sense, but here it (is supposed to) comes from a human source (your script, or a file, a user input).

Input from a remote terminal (e.g. over a socket where I imagine many people are/will be using this library -- like myself) can vary. In the case of a file this is also a big issue. ANSI sprites/art/etc. which is still being produced by modern tools (Moebius and PabloDraw to name a couple) uses the legacy system of bold+color for bright colors. 

If I take the output of TerminalKit (which which uses a termconfig) and feed it right back to TerminalKit, it renders incorrectly since the input doesn't take the termconfig into account.

> Why don't you just use regular Terminal Kit markup? It's way easier to remember, less keystrokes, easier for eventual contributor, maintenance, and so on...

If I were using TerminalKit for something simple this may work, but I'm not. I'm using TerminalKit in a much larger system that already has to deal with other libraries and inputs (from remote terminals). Ranvier (a JS game engine) has pluggable markup language so I use one that can work there and here, and in other areas of my game that are using neither Ranvier or TerminalKit. In order to not have a ton of markup languages I use a single system that produces ANSI as per the terminal config that TerminalKit provides. To support all terminals this means for example "brightBlack"/grey is `ESC[1;30m`. The other half of the coin is TerminalKit's markup is quite limited for larger projects. The markup I'm using can for example specify custom colors and named colors -- e.g. to always use a pre-defined color for a "item". This is of course not something TerminalKit would want to do, but something someone using TerminalKit like myself would.

> To be honest, adding 'ansi' input was done for a specific use-case (someone wanted to highlight logs coming from another program, which seemed legit to me), but I'm not quite content with it, cause it leads to misunderstanding and misuses of the lib by users, and of course it increase the bug surface and maintenance cost on my side.

I want to re-iterate that I really appreciate what you're doing here. I'm not trying to be a pain in your butt :) I think you will find that others are going to want this as well for reasons similar to above. And certainly even moreso for text areas where one expects to be able to display "art" and have it render correctly (If you're unfamiliar with ANSI art this is a good resource: https://16colo.rs/) similar to what you can do in blessed and many other non-JS terminal libraries.

I hope that helps.

**Comment by cronvel** [comment]
@NuSkooler Ok I think the bug is fixed as of v2.0.3.

**Comment by NuSkooler** [comment]
@cronvel Seems to be working now!

Thanks again for supporting this. I hope the explanation above helps with the "why".
