### ISSUE TITLE
[Windows] time-out when writing while reading

### ISSUE THREAD

**Issue by minecrawler** [cronvel/terminal-kit#16]
My expectation is, that when having the following code

```js
'use strict';

const tk = require('terminal-kit').terminal;

tk('TEST\n> ');
tk.inputField({
    history: [],
}, (err, input) => {
    if (err) {
        throw err;
    }
    
    console.log('Your input: ' + input);
});

tk('TEST2\n');
```

I'd get an output of 

```
TEST
TEST2
> |
```

with the cursor at the pipe, or at least

```
TEST
> |
TEST2
```

But terminal-kit fails with the error

```
C:\Users\marco_000\tmp>node test.js
TEST
> TEST2
C:\Users\marco_000\tmp\test.js:10
        throw err;
        ^

Error: .getCursorLocation() timed out
    at Terminal.getCursorLocation (C:\Users\marco_000\tmp\node_modules\terminal-kit
\lib\Terminal.js:1118:50)
    at init (C:\Users\marco_000\tmp\node_modules\terminal-kit\lib\inputField.js:198
:8)
    at Terminal.inputField (C:\Users\marco_000\tmp\node_modules\terminal-kit\lib\in
putField.js:840:2)
    at Object.<anonymous> (C:\Users\marco_000\tmp\test.js:6:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by cronvel** [comment]
Thanks for reporting.
I assume you are using Windows from what I see in the error log (C:\.)
Windows terminals are awful, so I guess it doesn't support retrieving the cursor location.

I will try to patch that soon, if it is possible...

**Comment by danikaze** [comment]
Any terminal working on Windows for this? Any possible fix?
Because this kind of bug disables all kind of input from the user in this OS, which... makes almost nothing possible... :P

**Comment by jy95** [comment]
Same for me : 

> Error: .getCursorLocation() timed out

cmd or powershell KO ^^

**Comment by vrachels** [comment]
in Terminal.js
~line 1383
I had to change the register terminal callback to before the requestCursorLocation
apparently it was doing the callback immediately / synchronously.

**Comment by cronvel** [comment]
@vrachels Tell me more about that: you mean that when running Windows, the event fire immediately after the `this.requestCursorLocation()` line?
That's really surprising... `.requestCursorLocation()` is only outputting few escape sequence to the terminal, so no event could possibly kick in in between.

**Comment by vrachels** [comment]
That is correct.  Stepping through terminal-kit code, on my windows machine, debugging the modified code goes something like:
1 breakpoint at this.requestCursorLocation  > step in
2 send escapes > step out
3 breakpoint at terminal callback > continue
4 breakpoint at next line after this.requestCursorLocation

Initial testing with original code never hit the breakpoint in the terminal callback.  Since I'm used to threaded languages, I noticed the possible timing issue, swapped the registration order, and got the above behavior.

**Comment by cronvel** [comment]
@vrachels ???
I don't get it... Writing to STDOUT is not supposed to trigger STDIN events synchronously, and BTW there is no thread.
Windows does not work the way it should.
Anyway, I trust you and I swapped the 2 lines.

**Comment by cheesefinger** [comment]
@cronvel @vrachels issue still present in terminal-kit@1.17.12

{ Error: .getCursorLocation() timed out
    at Timeout.async.setSafeTimeout [as _onTimeout] (C:\Users\admin\nodejs\console\node_modules\terminal-kit\lib\Terminal.js:1368:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) code: 'timeout' }

**Comment by vrachels** [comment]
@cheesefinger do breakpoints in onTerminal (Terminal.js ~1355) hit?
before or after ~1368, or if you increase the timeout value ~1371?

just updated to latest and confirmed working without modification using w10 cmd and powershell

I did however notice that the git bash does fail.  It is reporting its type as 'pipe' instead of tty, meaning the control codes aren't likely even being processed.

try adding this line to detectTerminal.js::guessTerminal() ~46:
```throw new Error(`guess: ${isSSH} ${isTTY}`)```
and running again in your usual terminal.  If both values are false, it's likely just not trying to apply the control codes.  Try again with a different local console - cmd or powershell.

or for way too much info, use the line:
```throw new Error(`guess: ${isSSH} ${isTTY} ${JSON.stringify(require('util').inspect(process.stdout))}`);```

Whether this is cheesefinger's issue, @cronvel it might be nice to test and throw a different kind of error when requestCursorLocation (or similar functionality) is called (or times out) but the terminal is not supported, to at least make that particular use case less confusing.

**Comment by cronvel** [comment]
Hi @vrachels @cheesefinger,

Since detecting if running inside a terminal is simply done using `isTTY = !! process.stdout.isTTY`, if git-bash is not considered a TTY, then it is either an issue with git-bash, or an issue with the Windows version of Node.js.

Also, it's true it should throw a more meaningful error message, and should not wait for timeout.
Version v1.17.13 should fix that.

**Comment by cheesefinger** [comment]
Thanks for the response @cronvel @vrachels

onTerminal (1355) is never hit even with a 10s timeout.
I hadn't tried powershell but it produced the same results.

Behavior is observable when running unmodified input samples in  ./sample/

```
PS C:\nodejs\terminal-kit\sample> node .\input-field-doc1.js
Please enter your name:
Your name is '(undefined)'
```

Host is win7.

**Comment by vrachels** [comment]
@cheesefinger can you paste the output of the 'too much info' line added to detectTerminal.js?

**Comment by cheesefinger** [comment]
@vrachels 


```
Error: guess: false true 

WriteStream {
  connecting: false,
  _hadError: false,
  _handle: 
   TTY {
     writeQueueSize: 0,
     owner: [Circular],
     onread: [Function: onread] },
  _parent: null,
  _host: null,
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: 
   { end: { [Function: bound onceWrapper] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd] },
  _eventsCount: 3,
  _maxListeners: undefined,
  _writableState: 
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: 
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _bytesDispatched: 0,
  _sockname: null,
  _writev: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  columns: 300,
  rows: 42,
  _type: 'tty',
  fd: 1,
  _isStdio: true,
  destroySoon: [Function: destroy],
  _destroy: [Function],
  [Symbol(asyncId)]: 3,
  [Symbol(bytesRead)]: 0 }
```

**Comment by vrachels** [comment]
(I got nothing.  Looks like a tty to me!)

**Comment by cronvel** [comment]
@el00ruobuob AFAICT those terminals don't support requesting terminal information.

**Comment by el00ruobuob** [comment]
@cronvel however, Windows 10 cmd works just fine, that's strange.  
I hope to find a suitable command line interpreter for windows 8.
