### ISSUE TITLE
Error thrown puts the terminal into a bad state.

### ISSUE THREAD

**Issue by ashnur** [cronvel/terminal-kit#3]
Using the following code: 
``` javascript
var term = require('terminal-kit').terminal
term.grabInput( { mouse: 'button', focus: true } ) 
term.on( 'mouse' , function( name , data ) {}) 
setTimeout( function() { throw new Error('dafuq') } , 1 ) 
```

I get a terminal where my mouse actions are swallowed and instead some escape sequences are written into it.

This happens both with terminology and gnome-terminal.

**Comment by cronvel** [comment]
Hi,

This is not an issue related to a specific terminal, in fact .grabInput() change the terminal mode, so it send escape sequences containing data about the mouse button states. If nothing tell the terminal to
switch back to the normal mode, it will simply continue to work this way.

Typically, the code can be fixed using:
```javascript
process.on( 'exit' , function() { term.grabInput( false ) ; process.exit() ; } ) ;
var term = require('terminal-kit').terminal
term.grabInput( { mouse: 'button', focus: true } ) 
term.on( 'mouse' , function( name , data ) {}) 
setTimeout( function() { throw new Error('dafuq') } , 1 )
```

It's hard to tell if this should be done in the lib or in the userland code, because there are more than one way of cleaning a terminal. For example, it is possible to alter the terminal color palette (if the terminal supports that feature), but does that mean that the lib should restore the palette before closing? One may want to create an utility that just edit the palette, and so on... (for example: application keypad mode).

**Comment by ashnur** [comment]
Some people might actually want the default behavior, and the behavior and the workaround is perfectly logical, however someone like me, who is a complete beginner with terminals, might get caught off guard. I think if this could be put in a visible place, that's a fine solution. It helps if even *obvious* things are mentioned somewhere :).

**Comment by cronvel** [comment]
Ok, I understand. 

Since I can't imagine any use-case where one may want to leave its program with input grabbing on, I fixed it.
