### ISSUE TITLE
.gridMenu() indentation?

### ISSUE THREAD

**Issue by davidgatti** [cronvel/terminal-kit#45]
@cronvel I have quick questions. I was wondering, is there a way to set an indentation (tab char) when displaying the .gridMenu()? 

![screen shot 2017-08-28 at 4 25 17 pm](https://user-images.githubusercontent.com/411114/29778208-da947fe2-8c0e-11e7-85a7-48859fbed807.png)

I attached a screenshot to better show what I mean. I did try to use the following options: leftPadding, selectedLeftPadding, rightPadding and selectedRightPadding but with not ideal results. 

The issue is that when you move the cursor on top of a name, they get chopped off and weird things happens. 

I wonder if there is a way to do it :)

**Comment by davidgatti** [comment]
Damn you fast :D

**Comment by cronvel** [comment]
@davidgatti Thanks ;)

I don't know if it solves your issue, since it didn't deals with tab, but you can specify the *x* coordinate of the top-left menu's corner. 

If you know for sure the indentation level of your terminal, you should be ok. 

IMHO I would not rely on the tab char for that. Terminal-kit has `term.column()` that move the cursor on the desirable column.

**Comment by cronvel** [comment]
@davidgatti Also I've added just now all available (low-level) tab manipulation: [see the doc](https://github.com/cronvel/terminal-kit/blob/master/doc/low-level.md#ref.movingCursor) (last five methods of the cursor section).

**Comment by davidgatti** [comment]
ooo, cool. I'll play with the new toys tomorrow 🤓😁

**Comment by davidgatti** [comment]
@cronvel fantastic the `x`, `y` position worked perfectly :) now everything is beautiful 😘😋
