### ISSUE TITLE
ansi escape sequences dont work with textbuffers

### ISSUE THREAD

**Issue by Luigimaster1** [cronvel/terminal-kit#78]
If I just write something like this:
`messagec.setText("\u001b[90mHello!")` (messagec is a TextBuffer)
then it displays ` [90mHello!`, which isn't exactly what I want.
The expected output is `Hello!` in gray.

**Comment by cronvel** [comment]
@Luigimaster1 Yes, because it isn't made to work this way. The TextBuffer separates the text from the attributes, so everything you pass to `.setText()` is considered pure raw text. There are `.setAttr()` and friends methods to do that.

**Comment by Floofies** [comment]
I am affected by this issue because [I am inserting `console.log` output into a TextBuffer](https://github.com/Floofies/hertzscript-dispatcher/blob/master/bin/cREPL.js), which will sometimes wrap the output string with ANSI escape sequences. How can I avoid this problem?

**Comment by cronvel** [comment]
@Floofies Ok I understand the use-case. I will look into it after holidays.

**Comment by cronvel** [comment]
@Luigimaster1 @Floofies So, there is still no escape sequences support at the moment, but there is a new support for _markup_ since v1.28.33.
In case you miss the markup feature, it allows things like this:

```js
// Output the word 'green' in green and 'red' in red
term( 'This is ^Ggreen^ and this is ^Rred^ !\n' ) ;
```

Now `TextBuffer#setContent()` supports those markup, [see the .setContent() doc](/cronvel/terminal-kit/blob/master/doc/textbuffer.md#ref.TextBuffer.setText), and also [the markup doc](/cronvel/terminal-kit/blob/master/doc/markup.md#top)

@Floofies I'm aware that this doesn't solve your issue, but to be honest, your use-case is **way too specific** to make it into the lib. You may want to use a module like *strip-ansi* before passing the `console.log()` output to a `TextBuffer`. One of the major goal of this lib is **to not** use (and know) any obscure terminal escape sequences and let the lib deals with them for you.

For instance, I will close the issue.
