### ISSUE TITLE
Error: Cannot find module 'lazyness'

### ISSUE THREAD

**Issue by jakecodes** [cronvel/terminal-kit#80]
I installed the package from node, required it as 
const term = require('terminal-kit').terminal
term('hello\n')
npm index
and I get this error....

**Comment by cronvel** [comment]
`npm index` ?

**Comment by jakecodes** [comment]
I ment node index to run the program idk why I typed npm sorry. But yeah I still get this error

**Comment by cronvel** [comment]
@jakecodes No offense but it seems to me that the problem is on your end.
First, how did you get terminal-kit? Did you `git clone` it or `npm install` it? Which terminal-kit version? The latest?

* If you used `npm install terminal-kit`, was there any error in the console when you installed it?
* If you used `git clone`, have you type `npm install` inside the `terminal-kit` repository? can you list files inside `terminal-kit/node_modules`?

What is your OS and your Node.js version?

**Comment by jakecodes** [comment]
I used npm install terminal-kit and don’t worry I’m not offended at all maybe I did make a dumb mistake. Just here to learn so I’m not embarrassed to ask questions haha
